//authentification action
export const LOADING_START = "LOADING_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOADING_STOP = "LOADING_STOP";
export const AUTH_ERROR = "AUTH_ERROR";

//ticket action types
export const GET_ALL_TICKET_SUCCESS = "GET_ALL_TICKET_SUCCESS";
export const GET_ALL_TICKET_FAIL = "GET_ALL_TICKET_FAIL";

export const GET_HELPING_TICKETS = "GET_HELPING_TICKETS";
export const GET_PENDING_TICKETS = "GET_PENDING_TICKETS";
export const GET_FIXED_TICKETS = "GET_FIXED_TICKETS";

export const GET_MY_TICKETS = "GET_MY_TICKETS";
export const GET_MY_HELPING_TICKETS = "GET_MY_HELPING_TICKETS";
